# Unique

In [8]:
# Unique() ---> It will return 3 arrays.
# arr ---> Unique elements of array
# return_index=True ---> Return indexing of unique elements
# return_counts=True ---> Return frequency of unique elements.

In [3]:
import numpy as np

In [5]:
a = np.array([1,2,3,1,1,1,2,4,5])
a

array([1, 2, 3, 1, 1, 1, 2, 4, 5])

In [7]:
np.unique(a, return_index=True, return_counts=True)

(array([1, 2, 3, 4, 5]),
 array([0, 1, 2, 7, 8], dtype=int64),
 array([4, 2, 1, 1, 1], dtype=int64))

In [9]:
# linspace() ---> It will create an array in which gap of values will be equal.
# syntax: np.linspace(min, max, total_numbers)

In [13]:
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

# Hstack and Vstack

In [29]:
# Hstack ---> It will combined all the in horizontally.
# Vstack --> It will combined all the array in vertically.

In [31]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,1])
c = np.array([9,10,11,1])

In [33]:
np.hstack((a,b,c)) # It will combined horeizontally

array([ 1,  2,  3,  4,  5,  6,  7,  1,  9, 10, 11,  1])

In [35]:
np.vstack((a,b,c)) # It will combined vertically.

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  1],
       [ 9, 10, 11,  1]])

# Pandas ---> Pandas is an open-source library of python that is used handle data maniuplations.

In [41]:
#!pip install pandas

In [43]:
import pandas as pd

In [45]:
# Data Structure of Pandas
# (a). Series --> It is one-dimensional array and it shows only values.
# (b). DataFrame ---> It is multi-dimensional array and it contains values with column name.

# (a). Series

In [49]:
a = pd.Series([1,45,78,90])
a

0     1
1    45
2    78
3    90
dtype: int64

In [51]:
type(a)

pandas.core.series.Series

# (b). DataFrame

In [57]:
a = {
    "Emp_ID":[1,2,3,4,5],
    "Name": ['Sam','Raj','Mohit','Aniket','Pallavi',],
    "Department": ['IT','Sales','Sales','IT','IT'],
    "Salary":[2000,45555,55522,5544,55222]
}

In [59]:
df = pd.DataFrame(a)
df

Emp_ID     Name Department  Salary
0       1      Sam         IT    2000
1       2      Raj      Sales   45555
2       3    Mohit      Sales   55522
3       4   Aniket         IT    5544
4       5  Pallavi         IT   55222

In [61]:
df.to_csv("C:\\Users\\Amanj\\OneDrive\\Desktop\\Aman\\emp_info.csv" , index=False)