# Introduction to Numpy ---->

In [4]:
# Numpy is an open-source library of python which is used for handle scintific-calcuations.

In [6]:
# !pip install numpy

In [8]:
import numpy as np

# Why Numpy is better than list ?

In [12]:
# 1. Numpy is homogenous data type and list is hetrogeneous data type.
# 2. Numpy takes less memory while list take more memmory.
# 3. Numpy take less execution time while list take more time of execution.
# 4. Numpy has more functionality as compare to list

In [14]:
a = [1,34,68,90]
type(a)

list

In [16]:
b = np.array(a)
b

array([ 1, 34, 68, 90])

In [18]:
type(b)

numpy.ndarray

In [20]:
a = [[1,2,3] , [4,5,6] , [7,8,9]]
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
print("Total Rows and Colums:", b.shape) # shape = n(rows) , n(columns)
print("Total Elements:", b.size) # size = n(rows) * n(columns)
print("Total Dimension:", b.ndim) # ndim stands for n_dimension here 2 = (x,y)

Total Rows and Colums: (3, 3)
Total Elements: 9
Total Dimension: 2


# User-Defined Array

In [26]:
a = []
size = int(input("Enter size:"))
for i in range(size):
    val = int(input("Enter item:"))
    a.append(val)

#a
b = np.array(a)
b

Enter size: 3
Enter item: 12
Enter item: 45
Enter item: 788


array([ 12,  45, 788])

# Functions in Numpy

In [30]:
# 1. Zero() --> It will create an array in which all the values will be 0 in either one- dimension
# or mulit-dimension.

In [32]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [34]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
# 2. Ones() ---> It will create an array in which all the values will be 1 in either one 
# dimensional or multi-dimensional.

In [38]:
a = np.ones(3)
a

array([1., 1., 1.])

In [40]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
# 3. Eye() --> It will create an array in which digonal positional elements will be 1 and
# rest all are 0 .

In [44]:
a = np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [46]:
# 4. Diag() ---> We can set custom values on digonal position.

In [48]:
a = np.array([12,34,67,90])
a

array([12, 34, 67, 90])

In [50]:
b = np.diag(a)
b

array([[12,  0,  0,  0],
       [ 0, 34,  0,  0],
       [ 0,  0, 67,  0],
       [ 0,  0,  0, 90]])

In [52]:
# 5. Random Module ---->
# (a). Randint() ---> It will generate random numbers in a given range.


In [58]:
a = np.random.randint(1,10,3)
a

array([2, 5, 7])

In [60]:
# (b). Rand() ----> It will generate random numbers in range 0-1.

In [62]:
a = np.random.rand(4)
a

array([0.77070701, 0.46265153, 0.46868078, 0.47726435])

In [64]:
# (c). Seed() ----> It will fix our random generated data.

In [68]:
np.random.seed(55)
a = np.random.randint(1,10,3)
a

array([8, 9, 6])

# Reshaping the Array
n(rows) * n(columns) = n(total_elements)

In [71]:
a = np.random.randint(1,50,12)
a

array([38, 28, 34, 49, 36, 47, 31, 14, 31, 13, 25, 48])

In [73]:
a.size

12

In [75]:
# 12 ---> reshape
# 1*12 ,  12*1
# 2*6, 6*2
# 3*4, 4*3

In [77]:
a.reshape(2,6)

array([[38, 28, 34, 49, 36, 47],
       [31, 14, 31, 13, 25, 48]])

In [79]:
a.reshape(3,4)

array([[38, 28, 34, 49],
       [36, 47, 31, 14],
       [31, 13, 25, 48]])

In [85]:
a.reshape(4,3)

array([[38, 28, 34],
       [49, 36, 47],
       [31, 14, 31],
       [13, 25, 48]])

In [87]:
a.reshape(2,5)

ValueError: cannot reshape array of size 12 into shape (2,5)

# Operations On Array

In [91]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [93]:
a > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [95]:
b = a>10
a[b]

array([11, 12, 13, 14, 15])

In [97]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [99]:
a = a.reshape(5,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [101]:
np.sum(a) ## total sum

120

In [103]:
np.sum(a, axis = 0) ## column wise sum ( axis=0 in numpy)

array([35, 40, 45])

In [105]:
np.sum(a, axis =1) # row wise sum ( aixs = 1 in numpy)

array([ 6, 15, 24, 33, 42])

In [107]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [109]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [111]:
a + b

array([[ 6,  8],
       [10, 12]])

In [115]:
a - b

array([[-4, -4],
       [-4, -4]])

In [117]:
a * b

array([[ 5, 12],
       [21, 32]])

In [121]:
a * b # matrix multiply is not this.

array([[ 5, 12],
       [21, 32]])

In [123]:
a.dot(b) ## dot() we can multiply of matrix.

array([[19, 22],
       [43, 50]])

In [125]:
a = np.array([1,2,3,4])
a**2

array([ 1,  4,  9, 16])

In [127]:
a**3

array([ 1,  8, 27, 64], dtype=int32)

In [129]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [131]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])